app = "research-assistant-client"
primary_region = "lax"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "80"
  VITE_API_URL = "https://research-assistant-server.fly.dev/research"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[checks]
  [checks.static_check]
    type = "http"
    port = 80
    path = "/"
    interval = "30s"
    timeout = "5s"
    grace_period = "30s"
