app = "research-assistant-client"
primary_region = "lax"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "80"
  VITE_API_URL = "https://research-assistant-api.fly.dev/research"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1 