app = "research-assistant-server"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "3001"
  NODE_ENV = "production"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[checks]
  # Name this check however you like
  [checks.http_status]
    type = "http"
    port = 3001
    method = "GET"
    path = "/health"
    interval = "30s"
    timeout = "5s"
    grace_period = "60s"

[[services.ports]]
  internal_port = 3001
  port = 443
  handlers = ["tls", "http"]
  force_https = true

[[services.ports]]
  internal_port = 3001
  port = 80
  handlers = ["http"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
