# fly.toml app configuration file generated for deep-research-api on 2025-02-16T18:04:17Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'deep-research-api'
primary_region = 'lhr'

[build]

[env]
  PORT = "3001"
  NODE_ENV = "production"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[checks]
  # Health check to confirm your server is up and responding
  [checks.server_check]
    type = "http"
    port = 3001
    path = "/health"
    interval = "30s"
    timeout = "5s"
    grace_period = "60s"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
