name: Deploy to Fly.io

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy apps
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      #############################
      # Client Build & Deployment #
      #############################
      - name: Install Client Dependencies
        working-directory: ./client
        run: npm ci

      - name: Build Client
        working-directory: ./client
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
        run: npm run build

      - name: Deploy Client to Fly.io
        working-directory: ./client
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy --remote-only --app deep-research-frontend

      #############################
      # Server Build & Deployment #
      #############################
      - name: Install Server Dependencies
        working-directory: ./server
        run: npm ci

      - name: Build Server
        working-directory: ./server
        run: npm run build

      - name: Update Server Secrets
        working-directory: ./server
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl secrets set \
            OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}" \
            OPENAI_MODEL="${{ secrets.OPENAI_MODEL }}" \
            FIRECRAWL_KEY="${{ secrets.FIRECRAWL_KEY }}" \
            FIRECRAWL_BASE_URL="${{ secrets.FIRECRAWL_BASE_URL }}" \
            CONTEXT_SIZE="${{ secrets.CONTEXT_SIZE }}" \
            --app deep-research-api

      - name: Deploy Server to Fly.io
        working-directory: ./server
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy --remote-only --app deep-research-api
